services:
  db:
    container_name: postgres_Bank
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Bank-DB
    volumes:
       - db_data:/var/lib/postgresql/data
    ports:
       - "5433:5432"

  pgadmin:
    container_name: pgadmin4_Bank
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: abdalouafi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
       - "8082:80"
volumes:
  db_data: